"""Graph layer for the unified node/edge model (see ADR-0032/0033).

Facade package: the graph service is split into domain modules (core, projects,
tasks, labels, cycles, identities, goals) but every name is re-exported here so
call sites keep using ``from app.services import graph`` / ``graph.create_task``
unchanged. Private helpers consumed across modules or by tests (``_project_view``,
``_log_event``, ...) are re-exported deliberately.

Internal dependency order (acyclic): core <- projects <- tasks <- cycles;
labels/identities/goals build on core (+ projects). ``tasks.delete_container``
reaches labels/cycles via deferred imports.
"""

from app.services.graph.core import (
    _TASK_DATA_SCALARS,
    NODE_CYCLE,
    NODE_GOAL,
    NODE_IDENTITY,
    NODE_LABEL,
    NODE_PROJECT,
    NODE_TASK,
    REL_ASSIGNED_TO,
    REL_CONTAINS,
    REL_DEPENDS_ON,
    REL_IN_CYCLE,
    REL_LABELED,
    REL_MEMBER_OF,
    ROLE_CONTAINER,
    ROLE_SHAREABLE,
    ROLE_SUBSCRIBABLE,
    ROLE_TASK,
    ROLES,
    _apply_task_data_defaults,
    _iso,
    _log_event,
    _parse_dt,
    add_edge,
    ancestors_of,
    children_of,
    container_type_keys,
    create_node,
    delete_node,
    dependency_maps,
    dependent_ids,
    descendants_of,
    detect_cycle,
    ensure_node,
    find_node_by_share_token,
    find_subscribable_node_by_share_token,
    get_node,
    has_role,
    nearest_ancestor_of_type,
    neighbors,
    new_webhook_secret,
    node_is_shareable,
    node_is_subscribable,
    parents_of,
    prerequisite_ids,
    project_container_map,
    remove_edge,
    remove_edges,
    shareable_type_keys,
    subscribable_type_keys,
    task_type_keys,
    update_node,
)
from app.services.graph.cycles import (
    CycleView,
    _cycle_view,
    add_to_cycle,
    create_cycle,
    cycle_ids_for_task,
    cycle_project_map,
    cycles_for_task,
    cycles_in_project,
    delete_cycle,
    find_cycle_by_name,
    get_cycle,
    remove_from_cycle,
    task_ids_in_cycle,
    tasks_in_cycle,
    update_cycle,
)
from app.services.graph.goals import (
    GoalView,
    _goal_view,
    all_goals,
    create_goal,
    delete_goal,
    get_goal,
    goal_subtree_progress,
    link_goal_project,
    project_ids_for_goal,
    projects_for_goal,
    update_goal,
)
from app.services.graph.identities import (
    IdentityView,
    _identity_view,
    all_identities,
    create_identity,
    delete_identity,
    find_identity_by_share_token,
    get_identity,
    identities_for_project,
    identity_ids_for_project,
    link_membership,
    project_ids_for_identity,
    projects_for_identity,
    unlink_membership,
    update_identity,
)
from app.services.graph.labels import (
    LabelView,
    _label_view,
    create_label,
    decisions,
    delete_label,
    find_label_by_name,
    get_label,
    label_ids_for_task,
    label_names,
    label_project_map,
    label_ref_exists,
    labeled_ids_map,
    labels_for_task,
    labels_in_project,
    labels_map,
    set_label,
    unset_label,
    update_label,
)
from app.services.graph.projects import (
    ProjectView,
    _project_view,
    all_projects,
    child_container_ids,
    contained_task_ids,
    container_of_node,
    container_view,
    create_project,
    find_project_by_share_token,
    get_project,
    projects_by_ids,
    search_projects,
    unfiled_task_ids,
    update_project,
)
from app.services.graph.tasks import (
    _TASK_HOT_COLUMNS,
    ContainerStats,
    TaskView,
    _apply_task_fields,
    _containment_ids_map,
    _delete_task_node,
    child_task_ids_map,
    container_ids_map,
    container_subtree_stats,
    create_task,
    delete_container,
    delete_task_tree,
    find_task_by_callback_token,
    find_task_by_external,
    get_task,
    member_container_ids,
    member_project_ids,
    parent_task_map,
    project_id_of_task,
    project_ids_map,
    project_of_task,
    set_parent_task,
    subtask_ids_among,
    subtasks,
    subtree_task_ids,
    subtree_task_views,
    task_view,
    task_views_by_ids,
    task_views_for_ids,
    tasks_in_project,
    top_level_task_filter,
    update_task,
)
