"""baseline - existing schema

Revision ID: d30b32886576
Revises: 
Create Date: 2026-04-25 13:27:59.584613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30b32886576'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.alter_column('share_token',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_unique_constraint(None, ['share_token'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['parent_id'], ['id'])

    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('share_token',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
